### PR TITLE
Admin panel

### PR DESCRIPTION
**Pull request by rdok**
@PadawanTony Would you mind create a database dump/export and commit it?   

I did not have the database to test it.

### CODE REVIEW

**Comment by PadawanTony** [comment]
I don't understand what "Would you mind create a database dump/export and commit it" means :/

**Comment by rdok** [comment]
@PadawanTony this one http://stackoverflow.com/q/4494378/2790481

**Comment by rdok** [comment]
@PadawanTony 
1. This one http://stackoverflow.com/q/4494378/2790481  -- If you don't want the data to be publicly available export an empty database. 
2. Then store the *.sql to this project, and git commit. 
3. :)

**Comment by PadawanTony** [comment]
Yes but what do I do after I export the db?

**Comment by rdok** [comment]
@PadawanTony 

> **2. Then store the *.sql to this project, and git commit.**   

You can store this file to a new folder such as database/your_export.sql

**Comment by PadawanTony** [comment]
man I don't understand. Why would I export the db and put it in the project?

**Comment by rdok** [comment]
@PadawanTony How would you share the database with other developers then? Every time you make changes to it are you going to export, and send it to them over emails?

How about when you 3, 5 or even 10 projects that you maintain? Can you imagine how time consuming, and often annoying when someone makes a change to the database, would be for all the team? 

Optional info:  
This is exactly why we use [migrations](https://github.com/rdok/exam-preparation/blob/master/database/migrations/mysql/UsersTable.php#L14). Instead of importing the database, we just just one command, which upgrades our local database of the project to the newest one.

**Comment by PadawanTony** [comment]
ok but Even if I make changes to the db now, wouldn't I have to export it again and replace the one in the project?

**Comment by rdok** [comment]
True. But it's the closest thing we have to migrations. Else I would have to constantly poke you for new database exports lol--I change like 10 times daily between 4 operating systems between my laptop/tower :P, and I lost the one you had sent me once :)

**Comment by PadawanTony** [comment]
Ah ok. So that you can have it from whatever pc/OS/etc. I get it now.

Also, now we have conflict in this pull request. I think it is because I removed some spaces from AdminController.php 

Let me go back to how it was before and see if they are resolved

**Comment by rdok** [comment]
Xexe OK.

**Pull request merged**
